### PR TITLE
Add Undo Function

### PR DESCRIPTION
**Pull request by skeenp**
Adding undo function to the gui for polyline and polygon features. Removes the last vertex added to the geom.

### CODE REVIEW

**Comment by skeenp** [comment]
Sorry, back.png and back.svg should be in src\roam\resources\images, not src\roam\resources\

**Comment by NathanW2** [comment]
Cool. Thanks. Could you update the image locations and I can merge it. You can remove the PNG as we only use SVG icons.

**Comment by skeenp** [comment]
Updated

**Comment by NathanW2** [comment]
Thanks very much.

**Pull request merged**
